CREATE DATABASE FICHA_DE_REGISTRO_INDIVIDUAL;

USE FICHA_DE_REGISTRO_INDIVIDUAL;

CREATE TABLE REGISTRO(

IDREGISTRO INT PRIMARY KEY AUTO_INCREMENT,
POSSUI_CPF ENUM ('SIM','NÃO'),
CPF VARCHAR (15) NOT NULL,
ESTRANGEIRO ENUM ('SIM','NÃO'),
NÚMERO_CNS VARCHAR (15) NOT NULL,
NOME VARCHAR (100) NOT NULL,
SEXO ENUM ('MASCULINO','FEMININO','OUTRO'),
DATA_DE_NASCIMNETO DATE NOT NULL,
GESTANTE CHAR (1) NOT NULL,
RACA CHAR (1) NOT NULL,
INDÍGENA ENUM ('SIM','NÃO'),
POVO VARCHAR (30) NOT NULL,
ESCOLARIDADE  CHAR (1) NOT NULL,
OCUPACAO VARCHAR (10),
NOME_DA_MÃE VARCHAR (100) NOT NULL,
PAIS VARCHAR (10),
);

CREATE TABLE ENDEREÇO(
IDENDEREÇO INT PRIMARY KEY AUTO_INCREMENT,
CEP VARCHAR (10)NOT NULL,
UF CHAR (2) NOT NULL,
CÓD_MUNICÍPIO VARCHAR (10) NOT NULL,
CÓD_REGIONAL VARCHAR (10) NOT NULL,
CÓD-UNIDADE VARCHAR (10) NOT NULL,
BAIRRO VARCHAR (80) NOT NULL,
LOGRADORURO VARCHAR (80),
NÚMERO VARCHAR (10),
ID_REGISTRO INT,
FOREIGN KEY ID_REGISTRO
REFERENCES REGISTRO(IDREGISTRO)


);

CREATE TABLE SINTOMAS(
IDSINTOMAS INT PRIMARY KEY AUTO_INCREMENT,
DATA_NOTIFICACAO DATE NOT NULL,
SEMANA_NOTIFICACAO VARCHAR (10),
PRIMEIROS_SINTOMAS DATE,
SEMANA_DOS_PRIMEIROS_SINTOMAS VARCHAR (10),
FEBRE ENUM ('SIM','NÃO') NOT NULL,
TOSSE ENUM ('SIM','NÃO') NOT NULL,
DOR_DE_GARGANTA ENUM ('SIM','NÃO') NOT NULL,
DISPINEIA ENUM ('SIM','NÃO') NOT NULL,
DESCONFORTO_RESPIRATORIO ENUM ('SIM','NÃO') NOT NULL,
SATURACAO ENUM ('SIM','NÃO') NOT NULL,
DIARREIA ENUM ('SIM','NÃO') NOT NULL,
VOMITO ENUM ('SIM','NÃO') NOT NULL,
DOR_ABDOMINAL ENUM ('SIM','NÃO') NOT NULL,
FADIGA ENUM ('SIM','NÃO') NOT NULL,
PERDA_DE_OLFATO ENUM ('SIM','NÃO') NOT NULL,
PERDA_DE_PALADAR ENUM ('SIM','NÃO') NOT NULL,
OUTROS_SINTOMAS VARCHAR (50),
ID_SINTOMAS INT,
FOREIGN KEY (ID_SINTOMAS)
REFERENCES REGISTRO(IDREGISTRO)
);

CREATE TABLE FATORES_DE_RISCO(
IDRISCO INT PRIMARY KEY AUTO_INCREMENT,
PUERPERA ENUM ('SIM','NÃO') NOT NULL,
CARDIOPATIA ENUM ('SIM','NÃO') NOT NULL,
DOENCA_HEMATOLOGICA ENUM ('SIM','NÃO') NOT NULL,
SINDROME_DE_DOWN ENUM ('SIM','NÃO') NOT NULL,
HEPATICO ENUM ('SIM','NÃO') NOT NULL,
ASMA ENUM ('SIM','NÃO') NOT NULL,
DIABETES ENUM ('SIM','NÃO') NOT NULL,
DOENCA_NEUROLOGICA ENUM ('SIM','NÃO') NOT NULL,
IMUNODEFICIENCIA ENUM ('SIM','NÃO') NOT NULL,
DOENCA_RENAL ENUM ('SIM','NÃO') NOT NULL,
OBESIDADE ENUM ('SIM','NÃO') NOT NULL,
OUTROS_FATORES ENUM ('SIM','NÃO') NOT NULL,
DES_FATORES VARCHAR (50),
ID_RISCO INT,
FOREIGN KEY (ID_RISCO)
REFERENCES REGISTRO(IDREGISTRO)
);

CREATE TABLE VACINA_COVID_19(
IDVACINA INT PRIMARY KEY AUTO_INCREMENT,
VACINA_COVID ENUM ('SIM','NÃO') NOT NULL,
DATA_DA_1_DOSE DATE NOT NULL,
DATA_DA_2_DOSE DATE NOT NULL,
DOSE_REFORCO DATE ,
DATA_DO_2_REFORCO DATE,
FAB_VACINA_1_DOSE VARCHAR (80) NOT NULL,
FAB_VACINA_2_DOSE VARCHAR (80) NOT NULL,
FAB_REFORCO VARCHAR (80) ,
FAB_REFORCO_2 VARCHAR (80) ,
LOTE_1_DOSE VARCHAR (30) NOT NULL,
LOTE_2_DOSE VARCHAR (30) NOT NULL,
LOTE_REFORCO VARCHAR (30),
LOTE_REFORCO_2 VARCHAR (30)
VACINA_GRIPE ENUM ('SIM','NÃO') NOT NULL, 
DATA_VACINA DATE NOT NULL,
MAE_VACINOU  ENUM ('SIM','NÃO','IGNORADO') NOT NULL,
DATA_VACINA_MAE DATE,
MAE_AMAMENTA  ENUM ('SIM','NÃO', 'IGNORADO') NOT NULL,
VACINA_GRIPE_CRIANCA DATE,
DOSE_REFORCO_CRIANCA DATE,
DOSE_REFORCO_CRIANCA_2 DATE,
OUTRAS_DOSES VARCHAR (30),
ID_VACINA INT,
FOREIGN KEY (ID_VACINA)
REFERENCES REGISTRO(IDREGISTRO)
);




CREATE TABLE TRATAMENTO (
IDTRATAMENTO INT PRIMARY KEY AUTO_INCREMENT,
ANTIVIRAL ENUM ('SIM','NÃO') NOT NULL,
QUAL_ANTIVIRAL VARCHAR (50) NOT NULL,
INICIO_TRATAMENTO DATE,
ANTIVIRAL_COVID_19 VARCHAR (50),
INICIO_ANTIVIRAL_COVID_19 DATE,
INTERNACAO ENUM ('SIM','NÃO') NOT NULL,
DATA_INTERNACAO_SRAG DATE,
UF_INTERNACAO CHAR (2),
COD_REGIONAL_INTERNACAO VARCHAR (10) NOT NULL,
COD_MUNICIPAL_INTERNACAO VARCHAR (10) NOT NULL,
COD_CNES_INTERNACAO VARCHAR (10) NOT NULL,
INTERNADO_UTI ENUM ('SIM','NÃO') NOT NULL,
DATA_ENTRADA_UTI DATE,
DATA_SAIDA_UTI DATE,
SUPORTE_VENTILATORIO  ENUM ('SIM, INVASIVO''SIM, NÃO INVASIVO','NÃO') NOT NULL,
RAIO_X_TORAX  ENUM ('NORMAL','Infiltrado intersticial', 'Consolidação','Misto', 'Outro', 'Não realizado') NOT NULL,
RAIO_X_TORAX_OUTRO VARCHAR (50),
DATA_RAIO_X DATE,
ASPECTO_TOMOGRAFIA ENUM ('Tipico covid-19', 'Indeterminado covid-19',' Atípico covid-19', 'Negativo para Pneumonia', ' Outro', 'Não realizado') NOT NULL,
ASPECT_TOMOGRAFIA_OUTRO VARCHAR (30),
DATA_TOMOGRAFIA DATE,
AMOSTRA ENUM ('SIM','NÃO') NOT NULL,
TIPO_AMOSTRA VARCHAR (50),
DATA_COLETA DATE,
EVOLUCAO_DO_CASO VARCHAR (10) NOT NULL,
DATA_ALTA DATE NOT NULL,
DATA_OBITO DATE NOT NULL,
OBSERVACOES VARCHAR (100),
ID_TRATAMENTO INT,
FOREIGN KEY(ID_TRATAMENTO)
REFERENCES REGISTRO(IDREGISTRO)

);
CREATE TABLE TESTES(

IDTESTES INT PRIMARY KEY AUTO_INCREMENT,
REQUISICAO_GAL VARCHAR (30),
TIPO_DE_TESTE ENUM ('Imunofluorescência (IF)',' Teste rápido antigênico'),
DATA_RESULTADO DATE,
RESULTADO_TESTE ENUM ('positivo','Negativo','Inconclusivo', 'Não realizado ', 'Aguardando resultado'),
LABORATORIO_TESTE VARCHAR (70),
COD_CNES_LABORATORIO VARCHAR (10),
TESTE_ANTIGENICO ENUM ('SIM','NÃO') NOT NULL,
TIPO_INFLUENZA VARCHAR (20), /* SE SIM, QUAL TIPO DE INFLUENZA */
TESTE_SARS_CoV_2 VARCHAR (20)  NOT NULL,
TESTE_VSR VARCHAR (10) NOT NULL,
TESTE_PARAINFLUENZA_1 VARCHAR (10) NOT NULL,
TESTE_PARAINFLUENZA_2 VARCHAR (10) NOT NULL,
TESTE_PARAINFLUENZA_3 VARCHAR (10) NOT NULL,
TESTE_ADENOVIRUS VARCHAR (10) NOT NULL,
TESTE_OUTRO_VIRUS VARCHAR (10) NOT NULL,
OUTROS_VIRUS VARCHAR (50),
RESULTADO_TESTE_RT_PCR  ENUM ('positivo','Negativo','Inconclusivo', 'Não realizado ', 'Aguardando resultado'),
DATA_RESULTAO_RT_PCR DATE,
COD_CNES_LABORATORIO_RT_PCR VARCHAR (10)  NOT NULL,
TIPO_AMOSTRA_SARS_COV_2 VARCHAR (10)  NOT NULL,
DATA_COLETA_SARS_COV_2 DATE,
TIPO_SOROLOGIA VARCHAR (20) NOT NULL,
RESULTADO_TESTE_SARS_COV_2 VARCHAR (10) NOT NULL,
DATA_RESULTADO_SARS_COV_2 DATE NOT NULL,
CLASSIFICACAO_FINAL VARCHAR (50) NOT NULL,
OBSERVACOES VARCHAR (100),
NOME_PROFISSIONAL_RESPONSAVEL  VARCHAR (100) NOT NULL,
MATRICULA_CONSELHO VARCHAR (15) NOT NULL,
ID_TESTES INT,
foreign key (ID_TESTES)
REFERENCES REGISTRO(IDREGISTRO)


);



